// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaX2qqtqLcJnUJhMHWASVhNSeL1YxD8x0',
    appId: '1:724098486280:web:5e478eb594d62ecb9041bd',
    messagingSenderId: '724098486280',
    projectId: 'eventmanagerapp-4iv8qf',
    authDomain: 'eventmanagerapp-4iv8qf.firebaseapp.com',
    storageBucket: 'eventmanagerapp-4iv8qf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TP0qv5vRnunoXRlY8zM-9FGWWFlc-ag',
    appId: '1:724098486280:android:2bde76c04c2b66699041bd',
    messagingSenderId: '724098486280',
    projectId: 'eventmanagerapp-4iv8qf',
    storageBucket: 'eventmanagerapp-4iv8qf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNV0b8t0DBCxzB_hEvcd0zUQ1kYdkTGQ',
    appId: '1:724098486280:ios:0fa6edbd74c6984e9041bd',
    messagingSenderId: '724098486280',
    projectId: 'eventmanagerapp-4iv8qf',
    storageBucket: 'eventmanagerapp-4iv8qf.firebasestorage.app',
    androidClientId: '724098486280-hsgrmeq2f293i0l1ggvlel21vhma2ghk.apps.googleusercontent.com',
    iosClientId: '724098486280-2c79dokm9o7fb2r24pgmsks35evdqm76.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagerApplicationFinalproject',
  );

}